title: CryptooFun
description: Trading Simulator for newbies.
domain: "CryptooFun.github.io"
url: "https://CryptooFun.github.io" 
show_downloads: true
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
